DROP DATABASE IF EXISTS SGT;
CREATE DATABASE SGT DEFAULT CHARSET=UTF8 COLLATE utf8_general_ci;
USE SGT;

CREATE TABLE Usuarios (
    idUsuarios INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL,
    senha VARCHAR(10) NOT NULL
);

CREATE TABLE Tarefas (
    idTarefas INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    descricao VARCHAR(100) NOT NULL DEFAULT 'Tarefas',
    DataVencimento DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Pendente',
    usuario_id INT,
    FOREIGN KEY (usuario_id) REFERENCES Usuarios(idUsuarios)
);

DESCRIBE Usuarios;
DESCRIBE Tarefas;
SHOW TABLES;
